### ISSUE TITLE
L2.01 – Ajouter une action (ex. : jouer un son, afficher un message) lorsqu’un personnage marche sur certaines tuiles (une tuile spécifique exécute une action lorsqu’un personnage marche dessus).

### ISSUE THREAD

**Issue by SamSebille** [StackNoodles/CERT93#11]
Attention : l’action doit être personnalisable en lui passant une fonction (un peu comme les actions associées aux actifs). L’action ne doit être exécutée qu’une seule fois, qu’à l’entrée du personnage sur la tuile. Si le personnage quitte la tuile et revient, l’action sera exécutée à nouveau (une seule fois à l’entrée sur la tuile).

**Comment by QuentinGast** [comment]
Le visuel des tuiles doit il etre different?

**Comment by QuentinGast** [comment]
35c6ab8822e843abda44b0e4747f5f6baacd891c son
a47da83207975ebb5f40b9686fc14b3009d8d577 code
