### ISSUE TITLE
L2.02 – Ajouter des sommes de contrôle (checksums) sur les fichiers cornichons utilisés pour les niveaux.

### ISSUE THREAD

**Issue by SamSebille** [StackNoodles/CERT93#12]
Les valeurs des sommes de contrôle doivent être sauvegardée dans une configuration externe et statique.

**Comment by pilotemaryse** [comment]
Terminé avec 75e991ea932068883854282f29a5bf97559d6b82 . Des checksums sont ajoutés aux fichiers cornichons des niveaux. Le module hashlib a été utilisé. Par la suite, les checksums sont enregistrés dans config.ini.
