### ISSUE TITLE
L2.06 – Afficher un message au sujet de l'incident ("Incident de base de données au bureau 1") lorsqu'un appel au centre d’appels (helpdesk) est distribué (donc pour les incidents autres que ceux du centre d’appels).

### ISSUE THREAD

**Issue by SamSebille** [StackNoodles/CERT93#16]
Le message doit disparaître tranquillement ou être remplacé par un nouveau le cas échéant s'il ne s'est pas encore complètement effacé.

**Comment by mapleduck** [comment]
Regle
257ce17cf48987d4f4e51ff22253f113e2d1aa04
