### ISSUE TITLE
L2.08 – Remplacer les valeurs en dur identifiant les axes et les boutons des contrôleurs de jeu (gamepads) par des valeurs paramétrables et stockées dans un fichier de configuration.

### ISSUE THREAD

**Issue by SamSebille** [StackNoodles/CERT93#18]
Cette modification permet aussi de supporter d’autres contrôleurs que ceux utilisés initialement.

**Comment by pilotemaryse** [comment]
Terminé avec 2d88be2024b84d15697d4a526fac9416d1a05061 Les valeurs sont déplacées dans le fichier config.ini . Ensuite elles sont appelées dans dans input_manager avec settings.
