### ISSUE TITLE
L3.03 – Permettre de mettre la partie sur pause avec la barre d’espacement ou le bouton « select » d’un contrôleur de jeu (gamepad).

### ISSUE THREAD

**Issue by SamSebille** [StackNoodles/CERT93#23]
La même touche et le même bouton doit permettre de reprendre la partie. La partie peut être mise sur pause ou relancée à partir de n’importe quel dispositif d’entrée (et peu importe lequel a été utilisé pour mettre sur pause lors de la reprise).

**Comment by QuentinGast** [comment]
https://github.com/StackNoodles/CERT93/commit/ba3418b1f65ad7420a6022e21748f18313a1d3a3
