### ISSUE TITLE
L3.04 – Imposer un temps de travail pour le personnage lorsqu’il résout un incident. Pendant que le personnage travaille sur un incident, la minuterie de l’incident doit être mise en pause et celle du personnage doit s’écouler.

### ISSUE THREAD

**Issue by SamSebille** [StackNoodles/CERT93#24]
Une barre de progression doit s’afficher près du personnage. Le temps de travail est déterminé en fonction du temps d’expiration de l’incident (time_to_solve). Pour un incident correspondant à l’expertise du personnage : 10% du temps d’expiration. Pour un incident ne correspondant pas à l’expertise du personnage : c’est plus de travail, donc 20%. Un personnage est verrouillé sur l’incident lorsqu’il travaille dessus. Si un joueur veut le libérer, il doit appuyer sur un bouton prévu à cette fin (choisir le bouton). Si un personnage abandonne son travail sur un incident avant de l’avoir résolu, la minuterie de l’incident est repartie et le travail devra être repris du début s’il y a lieu. Attention : Hulk a l’expertise pour résoudre tous les incidents.

**Comment by QuentinGast** [comment]
https://github.com/StackNoodles/CERT93/commit/5bc94005b69ea0acb78a9b6241387a6d4ad629d6
