### ISSUE TITLE
L3.05 – Afficher des indicateurs de position des incidents et des personnages qui se trouvent à l’extérieur de la vue du joueur.

### ISSUE THREAD

**Issue by SamSebille** [StackNoodles/CERT93#25]

**Comment by SamSebille** [comment]
Chaque indicateur doit être positionné au rebord de la vue, sur une ligne invisible reliant le personnage actif à l’incident ou le personnage qui se trouve à l’extérieur de la vue. Le pointeur de l’indicateur (une petite flèche par exemple) doit également être orienté dans la bonne direction, donc dans le bon angle.

**Comment by QuentinGast** [comment]
https://github.com/StackNoodles/CERT93/commit/6d4d55f6cc81f09cb0ea110a5be38b525f6d98f1
