### ISSUE TITLE
L1.04 – Modifier le code pour éviter l’ajout au bureau de deux personnages ayant le même nom.

### ISSUE THREAD

**Issue by SamSebille** [StackNoodles/CERT93#4]
Même chose pour les actifs.

**Comment by mapleduck** [comment]
Solved issue with commit [dd9c6f0](https://github.com/StackNoodles/CERT93/commit/dd9c6f0546d137885636cf98b8af1804d8e2afcc). Program will append a number (ex: Christian#2) if there are duplicate names in the pickle file.
