### ISSUE TITLE
L1.06 – Utiliser des valeurs paramétrables (configurables) pour la sélection d’un temps de résolution des incidents autres que ceux du centre d’appels.

### ISSUE THREAD

**Issue by SamSebille** [StackNoodles/CERT93#6]
Prévoir une validation minimale sur les valeurs configurées : il faut des valeurs positives, il faut que le temps maximum soit supérieur au temps minimum.

**Comment by mapleduck** [comment]
Je pense être sur la bonne piste avec le commit [e04c949](https://github.com/stackNoodles/CERT93/commit/e04c949fa0279621bc0a51e437fa991ba7c78678).

J'ai trouvé que le constructeur de la classe incident avait comme paramètre time to solve, qui était généré randomly avec des chiffres en dur.  J'ai remplacé ceux-cis par des paramètres et je fais la validation.

C'est cela que j'ai intrepreté comme "la sélection d’un temps de résolution des incidents autres que ceux du centre d’appels" (en ce moment, il n'y a _pas_ d'autres incidents que ceux des appels, et ceux ci génèrent leur propre time to solve).

**Comment by mapleduck** [comment]
_"J’ai regardé ça me semble correct"_
- @QuentinGast
