### ISSUE TITLE
L1.07 – Convertir les « constantes » statiques utilisées par __IncidentSpawner pour la création des incidents en valeurs paramétrables (configurables).

### ISSUE THREAD

**Issue by SamSebille** [StackNoodles/CERT93#7]

**Comment by SamSebille** [comment]
Prévoir une validation minimale sur les valeurs configurées

**Comment by pilotemaryse** [comment]
Terminé avec 97ec25c29d531e13a3cc4018205948a4ce365dde - Les variables statiques sont maintenant paramétrables dans le fichier config.ini il y a un check minimal dans le __IncidentSpawner pour voir si les variables sont plus grandes que 0 et ainsi que le max est plus grand que le min
